@extends('layouts.dashboard')

@section('title', 'Appointment Management')

@section('content')
    <div class="p-6">
        <!-- Header -->
        <div class="flex justify-between items-center mb-6">
            <div class="flex items-center gap-2">
                <i class="fas fa-calendar-check w-6 h-6 text-gray-700"></i>
                <h1 class="text-2xl font-bold text-gray-800">Appointment Management</h1>
            </div>
        </div>

        <!-- Filters -->
        <div class="bg-white rounded-xl shadow-sm border border-gray-200 p-4 mb-6">
            <div class="grid grid-cols-1 md:grid-cols-4 gap-4">
                <div>
                    <input type="text" id="searchInput" placeholder="Search by name or service..."
                        class="w-full px-3 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-blue-500 focus:border-transparent">
                </div>
                <div>
                    <select id="statusFilter"
                        class="w-full px-3 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-blue-500 focus:border-transparent">
                        <option value="">All Status</option>
                        <option value="pending">Pending</option>
                        <option value="confirmed">Confirmed</option>
                        <option value="completed">Completed</option>
                        <option value="cancelled">Cancelled</option>
                    </select>
                </div>
                <div>
                    <input type="date" id="dateFilter"
                        class="w-full px-3 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-blue-500 focus:border-transparent">
                </div>
                <div>
                    <button onclick="applyFilters()"
                        class="w-full flex items-center justify-center gap-2 bg-blue-600 text-white px-4 py-2 rounded-lg hover:bg-blue-700 transition-colors">
                        <i class="fas fa-filter w-4 h-4"></i>
                        Apply Filters
                    </button>
                </div>
            </div>
        </div>

        <!-- Appointments Table -->
        <div class="bg-white rounded-xl shadow-sm border border-gray-200 overflow-hidden">
            <div class="overflow-x-auto">
                <table class="w-full">
                    <thead class="bg-gray-50 border-b border-gray-200">
                        <tr>
                            <th class="px-6 py-3 text-left text-sm font-semibold text-gray-700">Client</th>
                            <th class="px-6 py-3 text-left text-sm font-semibold text-gray-700">Service</th>
                            <th class="px-6 py-3 text-left text-sm font-semibold text-gray-700">Date & Time</th>
                            <th class="px-6 py-3 text-left text-sm font-semibold text-gray-700">Contact</th>
                            <th class="px-6 py-3 text-left text-sm font-semibold text-gray-700">Status</th>
                            <th class="px-6 py-3 text-left text-sm font-semibold text-gray-700">Actions</th>
                        </tr>
                    </thead>
                    <tbody id="appointmentsBody" class="divide-y divide-gray-200">
                        <!-- Appointments will be generated by JavaScript -->
                    </tbody>
                </table>
            </div>
        </div>
    </div>

    <!-- Reschedule Modal -->
    <div id="rescheduleModal" class="hidden fixed inset-0 bg-black/50 z-50 flex items-center justify-center p-4">
        <div class="bg-white rounded-xl shadow-xl max-w-md w-full">
            <div class="flex items-center justify-between p-6 border-b border-gray-200">
                <h3 class="text-lg font-semibold text-gray-800">Reschedule Appointment</h3>
                <button onclick="closeRescheduleModal()" class="text-gray-400 hover:text-gray-600">
                    <i class="fas fa-times w-5 h-5"></i>
                </button>
            </div>

            <form id="rescheduleForm" class="p-6 space-y-4">
                <input type="hidden" id="rescheduleId" value="">

                <div>
                    <label class="block text-sm font-medium text-gray-700 mb-2">New Date</label>
                    <input type="date" id="rescheduleDate"
                        class="w-full px-3 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-blue-500 focus:border-transparent"
                        required>
                </div>

                <div>
                    <label class="block text-sm font-medium text-gray-700 mb-2">New Time</label>
                    <input type="time" id="rescheduleTime"
                        class="w-full px-3 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-blue-500 focus:border-transparent"
                        required>
                </div>

                <div class="flex gap-3 pt-4">
                    <button type="button" onclick="closeRescheduleModal()"
                        class="flex-1 px-4 py-2 border border-gray-300 text-gray-700 rounded-lg hover:bg-gray-50 transition-colors">
                        Cancel
                    </button>
                    <button type="submit"
                        class="flex-1 px-4 py-2 bg-blue-600 text-white rounded-lg hover:bg-blue-700 transition-colors">
                        Reschedule
                    </button>
                </div>
            </form>
        </div>
    </div>

    @push('scripts')
        <script>
            let appointments = [{
                    id: 1,
                    client: 'Ahmad Susanto',
                    service: 'Pengesahan Dokumen',
                    date: '2024-12-28',
                    time: '10:00',
                    phone: '0812-3456-7890',
                    email: 'ahmad@example.com',
                    status: 'confirmed'
                },
                {
                    id: 2,
                    client: 'Siti Nurhaliza',
                    service: 'Akta Jual Beli',
                    date: '2024-12-28',
                    time: '14:00',
                    phone: '0813-4567-8901',
                    email: 'siti@example.com',
                    status: 'pending'
                },
                {
                    id: 3,
                    client: 'Budi Santoso',
                    service: 'Akta Pendirian PT',
                    date: '2024-12-29',
                    time: '09:00',
                    phone: '0814-5678-9012',
                    email: 'budi@example.com',
                    status: 'confirmed'
                },
                {
                    id: 4,
                    client: 'Rina Wijaya',
                    service: 'Konsultasi Hukum',
                    date: '2024-12-29',
                    time: '15:00',
                    phone: '0815-6789-0123',
                    email: 'rina@example.com',
                    status: 'completed'
                },
                {
                    id: 5,
                    client: 'Dani Prasetyo',
                    service: 'Legalisasi Dokumen',
                    date: '2024-12-30',
                    time: '11:00',
                    phone: '0816-7890-1234',
                    email: 'dani@example.com',
                    status: 'cancelled'
                },
            ];

            function getStatusBadge(status) {
                const badges = {
                    pending: 'bg-yellow-100 text-yellow-800 border-yellow-200',
                    confirmed: 'bg-blue-100 text-blue-800 border-blue-200',
                    completed: 'bg-green-100 text-green-800 border-green-200',
                    cancelled: 'bg-red-100 text-red-800 border-red-200',
                };
                const labels = {
                    pending: 'Pending',
                    confirmed: 'Confirmed',
                    completed: 'Completed',
                    cancelled: 'Cancelled',
                };
                return `<span class="px-3 py-1 rounded-full text-xs font-medium border ${badges[status]}">${labels[status]}</span>`;
            }

            function formatDateTime(date, time) {
                const d = new Date(date);
                const dateStr = d.toLocaleDateString('id-ID', {
                    day: 'numeric',
                    month: 'short',
                    year: 'numeric'
                });
                return `${dateStr} at ${time}`;
            }

            function renderAppointments(filteredAppointments = appointments) {
                const tbody = document.getElementById('appointmentsBody');
                tbody.innerHTML = '';

                if (filteredAppointments.length === 0) {
                    tbody.innerHTML =
                        '<tr><td colspan="6" class="px-6 py-8 text-center text-gray-500">No appointments found</td></tr>';
                    return;
                }

                filteredAppointments.forEach(apt => {
                    const row = document.createElement('tr');
                    row.className = 'hover:bg-gray-50';

                    row.innerHTML = `
            <td class="px-6 py-4">
                <div class="font-medium text-gray-900">${apt.client}</div>
                <div class="text-sm text-gray-500">${apt.email}</div>
            </td>
            <td class="px-6 py-4 text-gray-700">${apt.service}</td>
            <td class="px-6 py-4 text-gray-700">${formatDateTime(apt.date, apt.time)}</td>
            <td class="px-6 py-4 text-gray-700">${apt.phone}</td>
            <td class="px-6 py-4">${getStatusBadge(apt.status)}</td>
            <td class="px-6 py-4">
                <div class="flex items-center gap-2">
                    ${apt.status === 'pending' ? `
                                <button onclick="updateStatus(${apt.id}, 'confirmed')" class="p-2 text-green-600 hover:bg-green-50 rounded-lg transition-colors" title="Confirm">
                                    <i class="fas fa-check w-4 h-4"></i>
                                </button>
                            ` : ''}
                    ${apt.status !== 'completed' && apt.status !== 'cancelled' ? `
                                <button onclick="openRescheduleModal(${apt.id})" class="p-2 text-blue-600 hover:bg-blue-50 rounded-lg transition-colors" title="Reschedule">
                                    <i class="fas fa-calendar w-4 h-4"></i>
                                </button>
                                <button onclick="updateStatus(${apt.id}, 'cancelled')" class="p-2 text-red-600 hover:bg-red-50 rounded-lg transition-colors" title="Cancel">
                                    <i class="fas fa-times-circle w-4 h-4"></i>
                                </button>
                            ` : ''}
                    ${apt.status === 'confirmed' ? `
                                <button onclick="updateStatus(${apt.id}, 'completed')" class="p-2 text-purple-600 hover:bg-purple-50 rounded-lg transition-colors" title="Complete">
                                    <i class="fas fa-check-circle w-4 h-4"></i>
                                </button>
                            ` : ''}
                </div>
            </td>
        `;

                    tbody.appendChild(row);
                });

                // Icons auto-loaded
            }

            function applyFilters() {
                const search = document.getElementById('searchInput').value.toLowerCase();
                const status = document.getElementById('statusFilter').value;
                const date = document.getElementById('dateFilter').value;

                let filtered = appointments;

                if (search) {
                    filtered = filtered.filter(apt =>
                        apt.client.toLowerCase().includes(search) ||
                        apt.service.toLowerCase().includes(search)
                    );
                }

                if (status) {
                    filtered = filtered.filter(apt => apt.status === status);
                }

                if (date) {
                    filtered = filtered.filter(apt => apt.date === date);
                }

                renderAppointments(filtered);
            }

            function updateStatus(id, newStatus) {
                const index = appointments.findIndex(apt => apt.id === id);
                if (index !== -1) {
                    appointments[index].status = newStatus;
                    applyFilters();
                }
            }

            function openRescheduleModal(id) {
                const apt = appointments.find(a => a.id === id);
                if (apt) {
                    document.getElementById('rescheduleId').value = id;
                    document.getElementById('rescheduleDate').value = apt.date;
                    document.getElementById('rescheduleTime').value = apt.time;
                    document.getElementById('rescheduleModal').classList.remove('hidden');
                    // Icons auto-loaded
                }
            }

            function closeRescheduleModal() {
                document.getElementById('rescheduleModal').classList.add('hidden');
            }

            document.getElementById('rescheduleForm').addEventListener('submit', function(e) {
                e.preventDefault();

                const id = parseInt(document.getElementById('rescheduleId').value);
                const newDate = document.getElementById('rescheduleDate').value;
                const newTime = document.getElementById('rescheduleTime').value;

                const index = appointments.findIndex(apt => apt.id === id);
                if (index !== -1) {
                    appointments[index].date = newDate;
                    appointments[index].time = newTime;
                }

                closeRescheduleModal();
                applyFilters();
            });

            // Event listeners for filters
            document.getElementById('searchInput').addEventListener('input', applyFilters);
            document.getElementById('statusFilter').addEventListener('change', applyFilters);
            document.getElementById('dateFilter').addEventListener('change', applyFilters);

            // Initialize
            renderAppointments();
        </script>
    @endpush
@endsection
