@extends('layouts.dashboard')

@section('title', 'Bot Training')

@section('content')
    <div class="p-6">
        <!-- Header -->
        <div class="flex justify-between items-center mb-6">
            <div class="flex items-center gap-2">
                <i class="fas fa-robot w-6 h-6 text-gray-700"></i>
                <h1 class="text-2xl font-bold text-gray-800">Bot Training</h1>
            </div>
            <button onclick="openAddResponseModal()"
                class="flex items-center gap-2 bg-blue-600 text-white px-4 py-2 rounded-lg hover:bg-blue-700 transition-colors">
                <i class="fas fa-plus w-4 h-4"></i>
                Add Response
            </button>
        </div>

        <!-- Filters -->
        <div class="bg-white rounded-xl shadow-sm border border-gray-200 p-4 mb-6">
            <div class="flex gap-4">
                <button onclick="filterByCategory('')" class="px-4 py-2 rounded-lg transition-colors category-btn active"
                    data-category="">
                    All
                </button>
                <button onclick="filterByCategory('greeting')" class="px-4 py-2 rounded-lg transition-colors category-btn"
                    data-category="greeting">
                    Greeting
                </button>
                <button onclick="filterByCategory('service')" class="px-4 py-2 rounded-lg transition-colors category-btn"
                    data-category="service">
                    Service
                </button>
                <button onclick="filterByCategory('info')" class="px-4 py-2 rounded-lg transition-colors category-btn"
                    data-category="info">
                    Info
                </button>
                <button onclick="filterByCategory('booking')" class="px-4 py-2 rounded-lg transition-colors category-btn"
                    data-category="booking">
                    Booking
                </button>
                <button onclick="filterByCategory('general')" class="px-4 py-2 rounded-lg transition-colors category-btn"
                    data-category="general">
                    General
                </button>
            </div>
        </div>

        <!-- Responses Grid -->
        <div id="responsesGrid" class="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-4">
            <!-- Responses will be generated by JavaScript -->
        </div>
    </div>

    <!-- Add/Edit Response Modal -->
    <div id="responseModal" class="hidden fixed inset-0 bg-black/50 z-50 flex items-center justify-center p-4">
        <div class="bg-white rounded-xl shadow-xl max-w-2xl w-full">
            <div class="flex items-center justify-between p-6 border-b border-gray-200">
                <h3 id="modalTitle" class="text-lg font-semibold text-gray-800">Add Response</h3>
                <button onclick="closeResponseModal()" class="text-gray-400 hover:text-gray-600">
                    <i class="fas fa-times w-5 h-5"></i>
                </button>
            </div>

            <form id="responseForm" class="p-6 space-y-4">
                <input type="hidden" id="responseId" value="">

                <div>
                    <label class="block text-sm font-medium text-gray-700 mb-2">Category</label>
                    <select id="responseCategory"
                        class="w-full px-3 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-blue-500 focus:border-transparent"
                        required>
                        <option value="greeting">Greeting</option>
                        <option value="service">Service</option>
                        <option value="info">Info</option>
                        <option value="booking">Booking</option>
                        <option value="general">General</option>
                    </select>
                </div>

                <div>
                    <label class="block text-sm font-medium text-gray-700 mb-2">Trigger (Question/Keywords)</label>
                    <input type="text" id="responseTrigger"
                        class="w-full px-3 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-blue-500 focus:border-transparent"
                        placeholder="e.g., Halo, Hai, Selamat pagi" required>
                    <p class="text-xs text-gray-500 mt-1">Separate multiple triggers with commas</p>
                </div>

                <div>
                    <label class="block text-sm font-medium text-gray-700 mb-2">Response</label>
                    <textarea id="responseText" rows="4"
                        class="w-full px-3 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-blue-500 focus:border-transparent"
                        placeholder="Bot's response..." required></textarea>
                </div>

                <div class="flex gap-3 pt-4">
                    <button type="button" onclick="closeResponseModal()"
                        class="flex-1 px-4 py-2 border border-gray-300 text-gray-700 rounded-lg hover:bg-gray-50 transition-colors">
                        Cancel
                    </button>
                    <button type="submit"
                        class="flex-1 px-4 py-2 bg-blue-600 text-white rounded-lg hover:bg-blue-700 transition-colors">
                        Save
                    </button>
                </div>
            </form>
        </div>
    </div>

    @push('scripts')
        <script>
            let responses = [{
                    id: 1,
                    category: 'greeting',
                    trigger: 'Halo, Hai, Hi',
                    response: 'Halo! Selamat datang di layanan Notaris kami. Ada yang bisa saya bantu?'
                },
                {
                    id: 2,
                    category: 'greeting',
                    trigger: 'Selamat pagi, Selamat siang',
                    response: 'Selamat pagi! Terima kasih telah menghubungi kami. Bagaimana saya bisa membantu Anda hari ini?'
                },
                {
                    id: 3,
                    category: 'service',
                    trigger: 'Layanan, Jasa, Service',
                    response: 'Kami menyediakan berbagai layanan notaris seperti:\n- Akta Jual Beli\n- Akta Pendirian PT\n- Pengesahan Dokumen\n- Konsultasi Hukum\n\nLayanan mana yang Anda butuhkan?'
                },
                {
                    id: 4,
                    category: 'service',
                    trigger: 'Akta jual beli',
                    response: 'Untuk layanan Akta Jual Beli, kami memerlukan:\n- KTP penjual dan pembeli\n- Sertifikat tanah asli\n- PBB tahun terakhir\n- Surat persetujuan dari pasangan (jika sudah menikah)\n\nApakah Anda ingin membuat janji temu?'
                },
                {
                    id: 5,
                    category: 'info',
                    trigger: 'Jam buka, Jam operasional',
                    response: 'Jam operasional kami:\nSenin - Jumat: 09.00 - 17.00\nSabtu: 09.00 - 13.00\nMinggu & Tanggal Merah: Tutup'
                },
                {
                    id: 6,
                    category: 'info',
                    trigger: 'Alamat, Lokasi',
                    response: 'Kantor kami berlokasi di:\nJl. Sudirman No. 123\nJakarta Pusat 10220\n\nLandmark: Seberang Gedung BCA Tower'
                },
                {
                    id: 7,
                    category: 'booking',
                    trigger: 'Buat janji, Booking, Reservasi',
                    response: 'Tentu! Saya akan membantu Anda membuat janji temu. Silakan klik tombol "Book Appointment" di bawah untuk melanjutkan proses pembuatan janji.'
                },
                {
                    id: 8,
                    category: 'general',
                    trigger: 'Biaya, Harga, Tarif',
                    response: 'Untuk informasi biaya layanan, mohon hubungi kami langsung atau buat janji konsultasi. Biaya bervariasi tergantung jenis layanan dan kompleksitas dokumen.'
                },
            ];
            let currentFilter = '';

            function getCategoryBadge(category) {
                const badges = {
                    greeting: 'bg-green-100 text-green-800 border-green-200',
                    service: 'bg-blue-100 text-blue-800 border-blue-200',
                    info: 'bg-purple-100 text-purple-800 border-purple-200',
                    booking: 'bg-orange-100 text-orange-800 border-orange-200',
                    general: 'bg-gray-100 text-gray-800 border-gray-200',
                };
                const labels = {
                    greeting: 'Greeting',
                    service: 'Service',
                    info: 'Info',
                    booking: 'Booking',
                    general: 'General',
                };
                return `<span class="px-2 py-1 rounded text-xs font-medium border ${badges[category]}">${labels[category]}</span>`;
            }

            function renderResponses(filteredResponses = responses) {
                const grid = document.getElementById('responsesGrid');
                grid.innerHTML = '';

                if (filteredResponses.length === 0) {
                    grid.innerHTML = '<div class="col-span-full text-center py-8 text-gray-500">No responses found</div>';
                    return;
                }

                filteredResponses.forEach(resp => {
                    const card = document.createElement('div');
                    card.className =
                        'bg-white rounded-xl shadow-sm border border-gray-200 p-4 hover:shadow-md transition-shadow';

                    card.innerHTML = `
            <div class="flex items-start justify-between mb-3">
                ${getCategoryBadge(resp.category)}
                <div class="flex gap-2">
                    <button onclick="editResponse(${resp.id})" class="p-1 text-blue-600 hover:bg-blue-50 rounded transition-colors">
                        <i class="fas fa-edit w-4 h-4"></i>
                    </button>
                    <button onclick="deleteResponse(${resp.id})" class="p-1 text-red-600 hover:bg-red-50 rounded transition-colors">
                        <i class="fas fa-trash w-4 h-4"></i>
                    </button>
                </div>
            </div>
            <div class="mb-2">
                <p class="text-sm font-medium text-gray-700 mb-1">Trigger:</p>
                <p class="text-sm text-gray-600">${resp.trigger}</p>
            </div>
            <div>
                <p class="text-sm font-medium text-gray-700 mb-1">Response:</p>
                <p class="text-sm text-gray-600 line-clamp-3">${resp.response}</p>
            </div>
        `;

                    grid.appendChild(card);
                });

                // Icons auto-loaded
            }

            function filterByCategory(category) {
                currentFilter = category;

                // Update button styles
                document.querySelectorAll('.category-btn').forEach(btn => {
                    if (btn.dataset.category === category) {
                        btn.classList.add('active', 'bg-blue-600', 'text-white');
                        btn.classList.remove('bg-gray-100', 'text-gray-700');
                    } else {
                        btn.classList.remove('active', 'bg-blue-600', 'text-white');
                        btn.classList.add('bg-gray-100', 'text-gray-700');
                    }
                });

                const filtered = category ? responses.filter(r => r.category === category) : responses;
                renderResponses(filtered);
            }

            function openAddResponseModal() {
                document.getElementById('modalTitle').textContent = 'Add Response';
                document.getElementById('responseForm').reset();
                document.getElementById('responseId').value = '';
                document.getElementById('responseModal').classList.remove('hidden');
                // Icons auto-loaded
            }

            function closeResponseModal() {
                document.getElementById('responseModal').classList.add('hidden');
            }

            function editResponse(id) {
                const resp = responses.find(r => r.id === id);
                if (resp) {
                    document.getElementById('modalTitle').textContent = 'Edit Response';
                    document.getElementById('responseId').value = resp.id;
                    document.getElementById('responseCategory').value = resp.category;
                    document.getElementById('responseTrigger').value = resp.trigger;
                    document.getElementById('responseText').value = resp.response;
                    document.getElementById('responseModal').classList.remove('hidden');
                    // Icons auto-loaded
                }
            }

            function deleteResponse(id) {
                if (confirm('Are you sure you want to delete this response?')) {
                    const index = responses.findIndex(r => r.id === id);
                    if (index !== -1) {
                        responses.splice(index, 1);
                        filterByCategory(currentFilter);
                    }
                }
            }

            document.getElementById('responseForm').addEventListener('submit', function(e) {
                e.preventDefault();

                const id = document.getElementById('responseId').value;
                const responseData = {
                    category: document.getElementById('responseCategory').value,
                    trigger: document.getElementById('responseTrigger').value,
                    response: document.getElementById('responseText').value,
                };

                if (id) {
                    // Update existing
                    const index = responses.findIndex(r => r.id == id);
                    responses[index] = {
                        ...responses[index],
                        ...responseData
                    };
                } else {
                    // Add new
                    responseData.id = Math.max(...responses.map(r => r.id), 0) + 1;
                    responses.push(responseData);
                }

                closeResponseModal();
                filterByCategory(currentFilter);
            });

            // Initialize
            renderResponses();
        </script>

        <style>
            .line-clamp-3 {
                display: -webkit-box;
                -webkit-line-clamp: 3;
                -webkit-box-orient: vertical;
                overflow: hidden;
            }

            .category-btn {
                @apply bg-gray-100 text-gray-700;
            }

            .category-btn.active {
                @apply bg-blue-600 text-white;
            }
        </style>
    @endpush
@endsection
