@extends('layouts.dashboard')

@section('title', 'Schedule Management')

@section('content')
    <div class="p-6">
        <!-- Header -->
        <div class="flex justify-between items-center mb-6">
            <div class="flex items-center gap-2">
                <i class="fas fa-calendar w-6 h-6 text-gray-700"></i>
                <h1 class="text-2xl font-bold text-gray-800">Schedule Management</h1>
            </div>
            <button onclick="openAddScheduleModal()"
                class="flex items-center gap-2 bg-blue-600 text-white px-4 py-2 rounded-lg hover:bg-blue-700 transition-colors">
                <i class="fas fa-plus w-4 h-4"></i>
                Add Schedule
            </button>
        </div>

        <!-- Calendar View -->
        <div class="bg-white rounded-xl shadow-sm border border-gray-200">
            <div class="p-6 border-b border-gray-200">
                <div class="flex items-center justify-between">
                    <h2 class="text-lg font-semibold text-gray-800">Weekly Schedule</h2>
                    <div class="flex items-center gap-2">
                        <button onclick="previousWeek()" class="p-2 hover:bg-gray-100 rounded-lg transition-colors">
                            <i class="fas fa-chevron-left w-5 h-5 text-gray-600"></i>
                        </button>
                        <span id="weekLabel" class="text-sm font-medium text-gray-700 px-4"></span>
                        <button onclick="nextWeek()" class="p-2 hover:bg-gray-100 rounded-lg transition-colors">
                            <i class="fas fa-chevron-right w-5 h-5 text-gray-600"></i>
                        </button>
                        <button onclick="goToToday()"
                            class="ml-2 px-3 py-2 text-sm bg-gray-100 hover:bg-gray-200 rounded-lg transition-colors">
                            Today
                        </button>
                    </div>
                </div>
            </div>

            <!-- Calendar Grid -->
            <div class="overflow-x-auto">
                <table class="w-full">
                    <thead class="bg-gray-50">
                        <tr>
                            <th class="px-4 py-3 text-left text-sm font-semibold text-gray-700 w-24">Time</th>
                            <th class="px-4 py-3 text-left text-sm font-semibold text-gray-700">Monday</th>
                            <th class="px-4 py-3 text-left text-sm font-semibold text-gray-700">Tuesday</th>
                            <th class="px-4 py-3 text-left text-sm font-semibold text-gray-700">Wednesday</th>
                            <th class="px-4 py-3 text-left text-sm font-semibold text-gray-700">Thursday</th>
                            <th class="px-4 py-3 text-left text-sm font-semibold text-gray-700">Friday</th>
                            <th class="px-4 py-3 text-left text-sm font-semibold text-gray-700">Saturday</th>
                            <th class="px-4 py-3 text-left text-sm font-semibold text-gray-700">Sunday</th>
                        </tr>
                    </thead>
                    <tbody id="calendarBody" class="divide-y divide-gray-200">
                        <!-- Time slots will be generated by JavaScript -->
                    </tbody>
                </table>
            </div>
        </div>
    </div>

    <!-- Add/Edit Schedule Modal -->
    <div id="scheduleModal" class="hidden fixed inset-0 bg-black/50 z-50 flex items-center justify-center p-4">
        <div class="bg-white rounded-xl shadow-xl max-w-md w-full">
            <div class="flex items-center justify-between p-6 border-b border-gray-200">
                <h3 id="modalTitle" class="text-lg font-semibold text-gray-800">Add Schedule</h3>
                <button onclick="closeScheduleModal()" class="text-gray-400 hover:text-gray-600">
                    <i class="fas fa-times w-5 h-5"></i>
                </button>
            </div>

            <form id="scheduleForm" class="p-6 space-y-4">
                <input type="hidden" id="scheduleId" value="">

                <div>
                    <label class="block text-sm font-medium text-gray-700 mb-2">Day</label>
                    <select id="scheduleDay"
                        class="w-full px-3 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-blue-500 focus:border-transparent">
                        <option value="Monday">Monday</option>
                        <option value="Tuesday">Tuesday</option>
                        <option value="Wednesday">Wednesday</option>
                        <option value="Thursday">Thursday</option>
                        <option value="Friday">Friday</option>
                        <option value="Saturday">Saturday</option>
                        <option value="Sunday">Sunday</option>
                    </select>
                </div>

                <div>
                    <label class="block text-sm font-medium text-gray-700 mb-2">Start Time</label>
                    <input type="time" id="scheduleStartTime"
                        class="w-full px-3 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-blue-500 focus:border-transparent"
                        required>
                </div>

                <div>
                    <label class="block text-sm font-medium text-gray-700 mb-2">End Time</label>
                    <input type="time" id="scheduleEndTime"
                        class="w-full px-3 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-blue-500 focus:border-transparent"
                        required>
                </div>

                <div>
                    <label class="block text-sm font-medium text-gray-700 mb-2">Staff</label>
                    <select id="scheduleStaff"
                        class="w-full px-3 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-blue-500 focus:border-transparent">
                        <option value="Notaris A">Notaris A</option>
                        <option value="Notaris B">Notaris B</option>
                        <option value="Staff 1">Staff 1</option>
                        <option value="Staff 2">Staff 2</option>
                    </select>
                </div>

                <div class="flex gap-3 pt-4">
                    <button type="button" onclick="closeScheduleModal()"
                        class="flex-1 px-4 py-2 border border-gray-300 text-gray-700 rounded-lg hover:bg-gray-50 transition-colors">
                        Cancel
                    </button>
                    <button type="submit"
                        class="flex-1 px-4 py-2 bg-blue-600 text-white rounded-lg hover:bg-blue-700 transition-colors">
                        Save
                    </button>
                </div>
            </form>
        </div>
    </div>

    @push('scripts')
        <script>
            let currentWeekStart = new Date();
            let schedules = [{
                    id: 1,
                    day: 'Monday',
                    startTime: '09:00',
                    endTime: '12:00',
                    staff: 'Notaris A'
                },
                {
                    id: 2,
                    day: 'Monday',
                    startTime: '14:00',
                    endTime: '17:00',
                    staff: 'Notaris B'
                },
                {
                    id: 3,
                    day: 'Tuesday',
                    startTime: '10:00',
                    endTime: '13:00',
                    staff: 'Staff 1'
                },
                {
                    id: 4,
                    day: 'Wednesday',
                    startTime: '09:00',
                    endTime: '12:00',
                    staff: 'Notaris A'
                },
                {
                    id: 5,
                    day: 'Thursday',
                    startTime: '14:00',
                    endTime: '16:00',
                    staff: 'Staff 2'
                },
                {
                    id: 6,
                    day: 'Friday',
                    startTime: '09:00',
                    endTime: '12:00',
                    staff: 'Notaris B'
                },
            ];

            function getMonday(date) {
                const d = new Date(date);
                const day = d.getDay();
                const diff = d.getDate() - day + (day === 0 ? -6 : 1);
                return new Date(d.setDate(diff));
            }

            function formatDate(date) {
                return date.toLocaleDateString('id-ID', {
                    day: 'numeric',
                    month: 'short',
                    year: 'numeric'
                });
            }

            function updateWeekLabel() {
                const monday = getMonday(currentWeekStart);
                const sunday = new Date(monday);
                sunday.setDate(sunday.getDate() + 6);
                document.getElementById('weekLabel').textContent = `${formatDate(monday)} - ${formatDate(sunday)}`;
            }

            function generateTimeSlots() {
                const times = [];
                for (let hour = 8; hour <= 17; hour++) {
                    times.push(`${hour.toString().padStart(2, '0')}:00`);
                }
                return times;
            }

            function renderCalendar() {
                const timeSlots = generateTimeSlots();
                const days = ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday', 'Sunday'];
                const tbody = document.getElementById('calendarBody');
                tbody.innerHTML = '';

                timeSlots.forEach(time => {
                    const row = document.createElement('tr');
                    row.className = 'hover:bg-gray-50';

                    // Time column
                    const timeCell = document.createElement('td');
                    timeCell.className = 'px-4 py-3 text-sm text-gray-600 font-medium';
                    timeCell.textContent = time;
                    row.appendChild(timeCell);

                    // Day columns
                    days.forEach(day => {
                        const cell = document.createElement('td');
                        cell.className = 'px-4 py-3 border-l border-gray-100';

                        // Find schedules for this day and time
                        const daySchedules = schedules.filter(s => {
                            if (s.day !== day) return false;
                            const [startHour] = s.startTime.split(':').map(Number);
                            const [currentHour] = time.split(':').map(Number);
                            const [endHour] = s.endTime.split(':').map(Number);
                            return currentHour >= startHour && currentHour < endHour;
                        });

                        if (daySchedules.length > 0) {
                            daySchedules.forEach(schedule => {
                                const scheduleDiv = document.createElement('div');
                                scheduleDiv.className =
                                    'bg-blue-100 border border-blue-200 rounded p-2 mb-1 cursor-pointer hover:bg-blue-200 transition-colors text-xs';
                                scheduleDiv.innerHTML = `
                        <div class="font-medium text-blue-900">${schedule.startTime} - ${schedule.endTime}</div>
                        <div class="text-blue-700">${schedule.staff}</div>
                    `;
                                scheduleDiv.onclick = () => editSchedule(schedule);
                                cell.appendChild(scheduleDiv);
                            });
                        }

                        row.appendChild(cell);
                    });

                    tbody.appendChild(row);
                });

                // Icons auto-loaded
            }

            function openAddScheduleModal() {
                document.getElementById('modalTitle').textContent = 'Add Schedule';
                document.getElementById('scheduleForm').reset();
                document.getElementById('scheduleId').value = '';
                document.getElementById('scheduleModal').classList.remove('hidden');
                // Icons auto-loaded
            }

            function closeScheduleModal() {
                document.getElementById('scheduleModal').classList.add('hidden');
            }

            function editSchedule(schedule) {
                document.getElementById('modalTitle').textContent = 'Edit Schedule';
                document.getElementById('scheduleId').value = schedule.id;
                document.getElementById('scheduleDay').value = schedule.day;
                document.getElementById('scheduleStartTime').value = schedule.startTime;
                document.getElementById('scheduleEndTime').value = schedule.endTime;
                document.getElementById('scheduleStaff').value = schedule.staff;
                document.getElementById('scheduleModal').classList.remove('hidden');
                // Icons auto-loaded
            }

            function previousWeek() {
                currentWeekStart.setDate(currentWeekStart.getDate() - 7);
                updateWeekLabel();
            }

            function nextWeek() {
                currentWeekStart.setDate(currentWeekStart.getDate() + 7);
                updateWeekLabel();
            }

            function goToToday() {
                currentWeekStart = new Date();
                updateWeekLabel();
            }

            document.getElementById('scheduleForm').addEventListener('submit', function(e) {
                e.preventDefault();

                const id = document.getElementById('scheduleId').value;
                const scheduleData = {
                    day: document.getElementById('scheduleDay').value,
                    startTime: document.getElementById('scheduleStartTime').value,
                    endTime: document.getElementById('scheduleEndTime').value,
                    staff: document.getElementById('scheduleStaff').value,
                };

                if (id) {
                    // Update existing
                    const index = schedules.findIndex(s => s.id == id);
                    schedules[index] = {
                        ...schedules[index],
                        ...scheduleData
                    };
                } else {
                    // Add new
                    scheduleData.id = Math.max(...schedules.map(s => s.id), 0) + 1;
                    schedules.push(scheduleData);
                }

                closeScheduleModal();
                renderCalendar();
            });

            // Initialize
            updateWeekLabel();
            renderCalendar();
        </script>
    @endpush
@endsection
