@extends('layouts.dashboard')

@section('title', 'User Management')

@section('content')
    <div class="p-6">
        <!-- Header -->
        <div class="flex justify-between items-center mb-6">
            <div class="flex items-center gap-2">
                <i class="fas fa-users w-6 h-6 text-gray-700"></i>
                <h1 class="text-2xl font-bold text-gray-800">User Management</h1>
            </div>
            <button onclick="openAddUserModal()"
                class="flex items-center gap-2 bg-blue-600 text-white px-4 py-2 rounded-lg hover:bg-blue-700 transition-colors">
                <i class="fas fa-plus w-4 h-4"></i>
                Add User
            </button>
        </div>

        <!-- Users Table -->
        <div class="bg-white rounded-xl shadow-sm border border-gray-200 overflow-hidden">
            <div class="overflow-x-auto">
                <table class="w-full">
                    <thead class="bg-gray-50 border-b border-gray-200">
                        <tr>
                            <th class="px-6 py-3 text-left text-sm font-semibold text-gray-700">Name</th>
                            <th class="px-6 py-3 text-left text-sm font-semibold text-gray-700">Email</th>
                            <th class="px-6 py-3 text-left text-sm font-semibold text-gray-700">Role</th>
                            <th class="px-6 py-3 text-left text-sm font-semibold text-gray-700">Created</th>
                            <th class="px-6 py-3 text-left text-sm font-semibold text-gray-700">Actions</th>
                        </tr>
                    </thead>
                    <tbody id="usersBody" class="divide-y divide-gray-200">
                        <!-- Users will be generated by JavaScript -->
                    </tbody>
                </table>
            </div>
        </div>
    </div>

    <!-- Add/Edit User Modal -->
    <div id="userModal" class="hidden fixed inset-0 bg-black/50 z-50 flex items-center justify-center p-4">
        <div class="bg-white rounded-xl shadow-xl max-w-md w-full">
            <div class="flex items-center justify-between p-6 border-b border-gray-200">
                <h3 id="modalTitle" class="text-lg font-semibold text-gray-800">Add User</h3>
                <button onclick="closeUserModal()" class="text-gray-400 hover:text-gray-600">
                    <i class="fas fa-times w-5 h-5"></i>
                </button>
            </div>

            <form id="userForm" class="p-6 space-y-4">
                <input type="hidden" id="userId" value="">

                <div>
                    <label class="block text-sm font-medium text-gray-700 mb-2">Full Name</label>
                    <input type="text" id="userName"
                        class="w-full px-3 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-blue-500 focus:border-transparent"
                        required>
                </div>

                <div>
                    <label class="block text-sm font-medium text-gray-700 mb-2">Email</label>
                    <input type="email" id="userEmail"
                        class="w-full px-3 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-blue-500 focus:border-transparent"
                        required>
                </div>

                <div>
                    <label class="block text-sm font-medium text-gray-700 mb-2">Password</label>
                    <input type="password" id="userPassword"
                        class="w-full px-3 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-blue-500 focus:border-transparent">
                    <p class="text-xs text-gray-500 mt-1">Leave blank to keep current password</p>
                </div>

                <div>
                    <label class="block text-sm font-medium text-gray-700 mb-2">Role</label>
                    <select id="userRole"
                        class="w-full px-3 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-blue-500 focus:border-transparent"
                        required>
                        <option value="staff">Staff</option>
                        <option value="superadmin">Super Admin</option>
                    </select>
                </div>

                <div class="flex gap-3 pt-4">
                    <button type="button" onclick="closeUserModal()"
                        class="flex-1 px-4 py-2 border border-gray-300 text-gray-700 rounded-lg hover:bg-gray-50 transition-colors">
                        Cancel
                    </button>
                    <button type="submit"
                        class="flex-1 px-4 py-2 bg-blue-600 text-white rounded-lg hover:bg-blue-700 transition-colors">
                        Save
                    </button>
                </div>
            </form>
        </div>
    </div>

    <!-- Delete Confirmation Modal -->
    <div id="deleteModal" class="hidden fixed inset-0 bg-black/50 z-50 flex items-center justify-center p-4">
        <div class="bg-white rounded-xl shadow-xl max-w-md w-full">
            <div class="p-6">
                <div class="flex items-center justify-center w-12 h-12 bg-red-100 rounded-full mx-auto mb-4">
                    <i class="fas fa-exclamation-triangle w-6 h-6 text-red-600"></i>
                </div>
                <h3 class="text-lg font-semibold text-gray-800 text-center mb-2">Delete User</h3>
                <p class="text-gray-600 text-center mb-6">Are you sure you want to delete this user? This action cannot be
                    undone.</p>

                <div class="flex gap-3">
                    <button onclick="closeDeleteModal()"
                        class="flex-1 px-4 py-2 border border-gray-300 text-gray-700 rounded-lg hover:bg-gray-50 transition-colors">
                        Cancel
                    </button>
                    <button onclick="confirmDelete()"
                        class="flex-1 px-4 py-2 bg-red-600 text-white rounded-lg hover:bg-red-700 transition-colors">
                        Delete
                    </button>
                </div>
            </div>
        </div>
    </div>

    @push('scripts')
        <script>
            let users = [{
                    id: 1,
                    name: 'Super Admin',
                    email: 'admin@notary.com',
                    role: 'superadmin',
                    created: '2024-01-15'
                },
                {
                    id: 2,
                    name: 'Staff User',
                    email: 'staff@notary.com',
                    role: 'staff',
                    created: '2024-02-20'
                },
                {
                    id: 3,
                    name: 'Notaris A',
                    email: 'notaris.a@notary.com',
                    role: 'staff',
                    created: '2024-03-10'
                },
                {
                    id: 4,
                    name: 'Notaris B',
                    email: 'notaris.b@notary.com',
                    role: 'staff',
                    created: '2024-03-15'
                },
            ];
            let deleteUserId = null;

            function getRoleBadge(role) {
                if (role === 'superadmin') {
                    return '<span class="px-3 py-1 rounded-full text-xs font-medium border bg-purple-100 text-purple-800 border-purple-200">Super Admin</span>';
                }
                return '<span class="px-3 py-1 rounded-full text-xs font-medium border bg-blue-100 text-blue-800 border-blue-200">Staff</span>';
            }

            function formatDate(dateStr) {
                const d = new Date(dateStr);
                return d.toLocaleDateString('id-ID', {
                    day: 'numeric',
                    month: 'short',
                    year: 'numeric'
                });
            }

            function renderUsers() {
                const tbody = document.getElementById('usersBody');
                tbody.innerHTML = '';

                users.forEach(user => {
                    const row = document.createElement('tr');
                    row.className = 'hover:bg-gray-50';

                    row.innerHTML = `
            <td class="px-6 py-4">
                <div class="flex items-center gap-3">
                    <div class="w-10 h-10 bg-gradient-to-br from-blue-500 to-purple-600 rounded-full flex items-center justify-center text-white font-semibold">
                        ${user.name.charAt(0).toUpperCase()}
                    </div>
                    <div class="font-medium text-gray-900">${user.name}</div>
                </div>
            </td>
            <td class="px-6 py-4 text-gray-700">${user.email}</td>
            <td class="px-6 py-4">${getRoleBadge(user.role)}</td>
            <td class="px-6 py-4 text-gray-700">${formatDate(user.created)}</td>
            <td class="px-6 py-4">
                <div class="flex items-center gap-2">
                    <button onclick="editUser(${user.id})" class="p-2 text-blue-600 hover:bg-blue-50 rounded-lg transition-colors" title="Edit">
                        <i class="fas fa-edit w-4 h-4"></i>
                    </button>
                    <button onclick="openDeleteModal(${user.id})" class="p-2 text-red-600 hover:bg-red-50 rounded-lg transition-colors" title="Delete">
                        <i class="fas fa-trash w-4 h-4"></i>
                    </button>
                </div>
            </td>
        `;

                    tbody.appendChild(row);
                });

                // Icons auto-loaded
            }

            function openAddUserModal() {
                document.getElementById('modalTitle').textContent = 'Add User';
                document.getElementById('userForm').reset();
                document.getElementById('userId').value = '';
                document.getElementById('userPassword').required = true;
                document.getElementById('userModal').classList.remove('hidden');
                // Icons auto-loaded
            }

            function closeUserModal() {
                document.getElementById('userModal').classList.add('hidden');
            }

            function editUser(id) {
                const user = users.find(u => u.id === id);
                if (user) {
                    document.getElementById('modalTitle').textContent = 'Edit User';
                    document.getElementById('userId').value = user.id;
                    document.getElementById('userName').value = user.name;
                    document.getElementById('userEmail').value = user.email;
                    document.getElementById('userPassword').value = '';
                    document.getElementById('userPassword').required = false;
                    document.getElementById('userRole').value = user.role;
                    document.getElementById('userModal').classList.remove('hidden');
                    // Icons auto-loaded
                }
            }

            function openDeleteModal(id) {
                deleteUserId = id;
                document.getElementById('deleteModal').classList.remove('hidden');
                // Icons auto-loaded
            }

            function closeDeleteModal() {
                deleteUserId = null;
                document.getElementById('deleteModal').classList.add('hidden');
            }

            function confirmDelete() {
                if (deleteUserId) {
                    const index = users.findIndex(u => u.id === deleteUserId);
                    if (index !== -1) {
                        users.splice(index, 1);
                        renderUsers();
                    }
                }
                closeDeleteModal();
            }

            document.getElementById('userForm').addEventListener('submit', function(e) {
                e.preventDefault();

                const id = document.getElementById('userId').value;
                const userData = {
                    name: document.getElementById('userName').value,
                    email: document.getElementById('userEmail').value,
                    role: document.getElementById('userRole').value,
                };

                if (id) {
                    // Update existing
                    const index = users.findIndex(u => u.id == id);
                    users[index] = {
                        ...users[index],
                        ...userData
                    };
                } else {
                    // Add new
                    userData.id = Math.max(...users.map(u => u.id), 0) + 1;
                    userData.created = new Date().toISOString().split('T')[0];
                    users.push(userData);
                }

                closeUserModal();
                renderUsers();
            });

            // Initialize
            renderUsers();
        </script>
    @endpush
@endsection
